import { loadProxyConfig } from './proxy';
import { fetchYouTubeSubtitles } from './youtube';
import type { SubtitleSource, LogEntry } from '../types';

// 字幕获取编排器
// 降级链：manual → youtube 直拉 → youtube 走 webshare 代理 → （仅 demo 视频）硬编码 fallback
//
// 关键约束：fallback 只在 videoId === DEMO_VIDEO_ID 时启用。
// 其他视频 level 2/3 全部失败时返回 null，让上层报错让用户手动粘贴字幕——
// 避免「输入 A 视频，喂给 LLM 的是 B 视频字幕」的灾难。
//
// 每一步的成败都记录到 attempts 里，由上层塞入 session.logs，方便用户在 UI 日志面板看到字幕获取过程。

export interface SubtitleResult {
  // 字幕抓取失败时为 null（且 attempts 里全部为 success:false），
  // 上层据此返回 NO_SUBTITLES 错误，让用户走手动粘贴。
  subtitles: string | null;
  source: SubtitleSource;
  attempts: SubtitleAttempt[];
}

export interface SubtitleAttempt {
  step: 'manual' | 'youtube-direct' | 'youtube-proxy' | 'fallback';
  success: boolean;
  message: string;
}

// 演示视频 ID：YouTube xRh2sVcNXQ8（AI 革命：万亿美金之问）
// 仅该视频可走硬编码字幕兜底；其他视频字幕抓不到就失败，不能用 demo 字幕糊弄。
const DEMO_VIDEO_ID = 'xRh2sVcNXQ8';

// 演示视频字幕：YouTube xRh2sVcNXQ8（AI 革命：万亿美金之问）
// 只在 DEMO_VIDEO_ID 走 fallback 时使用，保证演示流程永远能跑通。
const DEMO_SUBTITLES = `[00:00] 今天我们要讨论一个价值万亿美元的问题
[00:15] 这就是 AI 革命的核心
[00:30] 我们看到 AI 行业正在经历前所未有的增长
[00:45] 收入正在爆发，成本正在塌陷
[01:00] 这是什么意思呢
[01:15] 意味着 AI 可以为企业和个人创造巨大价值
[01:30] 首先是消费者 AI 市场
[01:45] 然后是企业 AI 市场
[02:00] 最后是云服务和数据中心基础设施
[02:15] 我们看到 GPU 和数据中心供给正在改善
[02:30] 这将进一步扩大需求
[02:45] 十年内，AI 将无处不在

[03:00] 收入增长的关键在于几个方面
[03:15] 首先是消费者订阅模式
[03:30] 人们愿意为 AI 助手付费
[03:45] 这是一个新的市场
[04:00] 其次是企业市场
[04:15] 企业愿意为提高效率付费
[04:30] 按需付费的模式很灵活
[04:45] 基于价值的定价也越来越流行
[05:00] 这些都是健康的商业模式

[05:15] 成本塌陷同样重要
[05:30] GPU 价格在下降
[05:45] 数据中心效率在提升
[06:00] 这意味着更多人可以负担得起
[06:15] 需求会进一步扩大
[06:30] 这是一个正向循环
[06:45] 收入增长，成本下降
[07:00] 更多创新随之而来

[07:15] 我们还要考虑地域分布
[07:30] 亚洲市场增长迅速
[07:45] 欧洲市场也在快速发展
[08:00] 美国市场依然领先
[08:15] 但竞争格局在变化
[08:30] 未来会有更多元化的竞争者

[09:00] 技术进步的速度令人惊讶
[09:15] 五年前我们无法想象今天的状态
[09:30] 下一个五年会是什么样
[09:45] 我相信会更加激动人心
[10:00] AI 将渗透到每个行业
[10:15] 每个企业都需要思考如何拥抱 AI
[10:30] 这不是选择，而是必须

[11:00] 最后让我们谈谈人才
[11:15] AI 人才供不应求
[11:30] 培养下一代是关键
[11:45] 开源和教育的机会巨大
[12:00] 我们期待看到更多创新`;

export interface GetSubtitlesEnv {
  PROXY_HOST?: string;
  PROXY_PORT?: string;
  PROXY_USERNAME?: string;
  PROXY_PASSWORD?: string;
}

export async function getSubtitles(
  videoId: string,
  manualSubtitles: string | undefined,
  env: GetSubtitlesEnv
): Promise<SubtitleResult> {
  const attempts: SubtitleAttempt[] = [];

  // Level 1: 用户手动粘贴（最高优先级，永远生效）
  if (manualSubtitles && manualSubtitles.trim()) {
    const trimmed = manualSubtitles.trim();
    attempts.push({ step: 'manual', success: true, message: `手动粘贴字幕：${trimmed.length} 字符` });
    return { subtitles: trimmed, source: 'manual', attempts };
  }

  // Level 2: YouTube InnerTube 直拉（无代理，Cloudflare Worker 出口 IP 直接请求）
  try {
    const result = await fetchYouTubeSubtitles(videoId);
    attempts.push({
      step: 'youtube-direct',
      success: true,
      message: `直拉成功（语言 ${result.languageCode}${result.isAutoGenerated ? '/自动生成' : ''}）：${result.text.length} 字符`
    });
    return { subtitles: result.text, source: 'youtube', attempts };
  } catch (e) {
    attempts.push({
      step: 'youtube-direct',
      success: false,
      message: `直拉失败：${(e as Error).message}`
    });
  }

  // Level 3: 通过 webshare 代理重试（绕过 YouTube 验证码 / IP 风控）
  const proxy = loadProxyConfig(env as Record<string, string | undefined>);
  if (proxy) {
    try {
      const result = await fetchYouTubeSubtitles(videoId, { proxy });
      attempts.push({
        step: 'youtube-proxy',
        success: true,
        message: `代理拉取成功（${proxy.host}:${proxy.port}，语言 ${result.languageCode}${result.isAutoGenerated ? '/自动生成' : ''}）：${result.text.length} 字符`
      });
      return { subtitles: result.text, source: 'youtube-proxy', attempts };
    } catch (e) {
      attempts.push({
        step: 'youtube-proxy',
        success: false,
        message: `代理拉取失败：${(e as Error).message}`
      });
    }
  } else {
    attempts.push({
      step: 'youtube-proxy',
      success: false,
      message: '未配置 PROXY_HOST/PORT/USERNAME/PASSWORD，跳过代理重试'
    });
  }

  // Level 4: 硬编码兜底 —— 仅限演示视频
  // 其他视频的 level 2/3 全部失败时，必须返回 null 让上层报错，
  // 绝不能用 demo 字幕替换——那会让 LLM 生成与用户实际视频无关的文章。
  if (videoId === DEMO_VIDEO_ID) {
    attempts.push({
      step: 'fallback',
      success: true,
      message: '使用硬编码演示字幕兜底（仅限 demo 视频）'
    });
    return { subtitles: DEMO_SUBTITLES, source: 'fallback', attempts };
  } else {
    attempts.push({
      step: 'fallback',
      success: false,
      message: '非演示视频，无硬编码兜底；请手动粘贴字幕或配置 PROXY_* 走代理重试'
    });
    return { subtitles: null, source: 'fallback', attempts };
  }
}

// 把 attempts 转成 LogEntry，由 index.ts 塞入 session.logs。
export function attemptsToLogs(attempts: SubtitleAttempt[], createdAt: number): LogEntry[] {
  return attempts.map(a => ({
    timestamp: Date.now() - createdAt,
    level: a.success ? 'SUCCESS' : 'ERROR',
    message: `[字幕/${a.step}] ${a.message}`
  }));
}
