import { proxiedFetch, type ProxyConfig } from './proxy';
import { proxiedFetchViaSocks5 } from './proxy-socks5';

// 通过 YouTube InnerTube API + timedtext 端点拉字幕。
// 流程：
//   1. POST /youtubei/v1/player（Android client 上下文）→ 拿到 captionTracks 列表
//   2. 优先选 zh-CN，没有则选第一条
//   3. GET captionTrack.baseUrl → 拿到字幕 XML
//   4. 正则解析 <text start="..." dur="...">内容</text> → 转成 [mm:ss] 行
//
// 调用模式：传 proxy 走 webshare 隧道，不传走原生 fetch（适合本地 dev 验证基础流程）。

export interface YouTubeFetchOptions {
  proxy?: ProxyConfig | null;
  // 代理握手协议：'http-connect'（默认）或 'socks5'
  // webshare 等 endpoint 的实际协议类型不确定，调用方按需指定
  proxyProtocol?: 'http-connect' | 'socks5';
}

const INNERTUBE_URL = 'https://www.youtube.com/youtubei/v1/player?prettyPrint=false';
const ANDROID_UA = 'com.google.android.youtube/20.10.38 (Linux; U; Android 14)';
const ANDROID_CLIENT_VERSION = '20.10.38';

interface InnerTubePlayerResponse {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: Array<{
        baseUrl: string;
        languageCode?: string;
        kind?: string;
        name?: { simpleText?: string };
      }>;
    };
  };
  playabilityStatus?: { status?: string; reason?: string };
  videoDetails?: { title?: string };
}

export interface YouTubeSubtitleResult {
  text: string;                    // [mm:ss] 行格式
  languageCode: string;
  isAutoGenerated: boolean;
}

/**
 * 取 YouTube 字幕。失败时抛 Error。
 * 不做 fallback，由上层 subtitle.ts 编排兜底。
 */
export async function fetchYouTubeSubtitles(
  videoId: string,
  options: YouTubeFetchOptions = {}
): Promise<YouTubeSubtitleResult> {
  const player = await fetchInnerTubePlayer(videoId, options);

  if (player.playabilityStatus?.status && player.playabilityStatus.status !== 'OK') {
    throw new Error(`视频不可播放：${player.playabilityStatus.status} ${player.playabilityStatus.reason || ''}`);
  }

  const tracks = player.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  if (tracks.length === 0) {
    throw new Error('视频没有可用字幕轨');
  }

  const preferred = tracks.find(t => t.languageCode === 'zh-CN')
                 ?? tracks.find(t => t.languageCode === 'zh')
                 ?? tracks.find(t => t.languageCode?.startsWith('en'))
                 ?? tracks[0];

  const xml = await fetchTimedtextXml(preferred.baseUrl, options);
  const text = parseTimedtextXmlToLines(xml);
  if (!text.trim()) {
    // 直接看真实格式：原始 XML 前 200 字节附在错误里
    // （用 < 转义防日志面板 XSS）
    const preview = xml.slice(0, 200).replace(/</g, '&lt;');
    throw new Error(`字幕 XML 解析后为空（原始前 200 字节: ${preview}）`);
  }

  return {
    text,
    languageCode: preferred.languageCode || 'unknown',
    isAutoGenerated: preferred.kind === 'asr'
  };
}

async function fetchInnerTubePlayer(
  videoId: string,
  options: YouTubeFetchOptions
): Promise<InnerTubePlayerResponse> {
  const body = JSON.stringify({
    context: {
      client: {
        clientName: 'ANDROID',
        clientVersion: ANDROID_CLIENT_VERSION,
        hl: 'zh-CN',
        gl: 'CN'
      }
    },
    videoId
  });

  const headers = {
    'Content-Type': 'application/json',
    'User-Agent': ANDROID_UA,
    'Accept': 'application/json'
  };

  let raw: string;
  let status: number;
  if (options.proxy) {
    const fetchViaProxy = options.proxyProtocol === 'socks5' ? proxiedFetchViaSocks5 : proxiedFetch;
    const res = await fetchViaProxy({
      url: INNERTUBE_URL,
      method: 'POST',
      headers,
      body
    }, options.proxy);
    raw = res.body;
    status = res.status;
  } else {
    const res = await fetch(INNERTUBE_URL, { method: 'POST', headers, body });
    raw = await res.text();
    status = res.status;
  }

  if (status !== 200) {
    // 403/429 是 Cloudflare/YouTube 对当前出口 IP 风控的典型状态码，
    // 错误信息标注出来让用户知道该去配代理 / 手动粘贴。
    const isRiskControl = status === 403 || status === 429;
    const detail = isRiskControl
      ? `（可能 IP 风控，建议配置 PROXY_* 走代理重试）`
      : '';
    throw new Error(`InnerTube HTTP ${status}${detail}：${raw.slice(0, 200)}`);
  }

  try {
    return JSON.parse(raw) as InnerTubePlayerResponse;
  } catch (e) {
    throw new Error(`InnerTube 响应不是合法 JSON：${(e as Error).message}`);
  }
}

async function fetchTimedtextXml(
  url: string,
  options: YouTubeFetchOptions
): Promise<string> {
  const headers = {
    'User-Agent': ANDROID_UA,
    'Accept': 'application/xml,text/xml,*/*'
  };

  let raw: string;
  let status: number;
  if (options.proxy) {
    const fetchViaProxy = options.proxyProtocol === 'socks5' ? proxiedFetchViaSocks5 : proxiedFetch;
    const res = await fetchViaProxy({ url, method: 'GET', headers }, options.proxy);
    raw = res.body;
    status = res.status;
  } else {
    const res = await fetch(url, { headers });
    raw = await res.text();
    status = res.status;
  }

  if (status !== 200) {
    throw new Error(`timedtext HTTP ${status}：${raw.slice(0, 200)}`);
  }
  return raw;
}

// 把 timedtext XML 解析成 [mm:ss] 行。
// YouTube 字幕轨有两种格式：
//   - format="1"（老）: <text start="秒" dur="秒">内容</text>，属性顺序不固定
//   - format="3"（新）: <p t="毫秒" d="毫秒">内容</p>，t/d 是整数毫秒
// 通过头部 <timedtext format="N"> 决定走哪条解析。
// XML 实体只处理 5 个常见字符 + 数字字符引用，够覆盖 YouTube 字幕里的常见转义。
export function parseTimedtextXmlToLines(xml: string): string {
  // 头部没声明 format 但有 <p t= 块，按 format="3" 处理（保守）
  if (/<p\s+[^>]*\bt="\d+"/.test(xml)) {
    return parseFormat3(xml);
  }
  return parseFormat1(xml);
}

// format="1": <text start="12.345" dur="2.1">内容</text>
// 属性顺序不固定，分两步：先匹配 <text>...</text> 块，再在属性串里找 start=
function parseFormat1(xml: string): string {
  const lines: string[] = [];
  const blockRegex = /<text\s+([^>]*?)>([\s\S]*?)<\/text>/g;
  const startAttrRegex = /start="([\d.]+)"/;
  let match: RegExpExecArray | null;
  while ((match = blockRegex.exec(xml)) !== null) {
    const startMatch = match[1].match(startAttrRegex);
    if (!startMatch) continue;
    const start = Number(startMatch[1]);
    const text = decodeXmlEntities(match[2]).replace(/\s+/g, ' ').trim();
    if (text) lines.push(`${formatTime(start)} ${text}`);
  }
  return lines.join('\n');
}

// format="3": <p t="1200" d="2160">内容</p>，t/d 是整数毫秒
function parseFormat3(xml: string): string {
  const lines: string[] = [];
  const blockRegex = /<p\s+([^>]*?)>([\s\S]*?)<\/p>/g;
  const tAttrRegex = /\bt="(\d+)"/;
  let match: RegExpExecArray | null;
  while ((match = blockRegex.exec(xml)) !== null) {
    const tMatch = match[1].match(tAttrRegex);
    if (!tMatch) continue;
    const startSec = Number(tMatch[1]) / 1000;
    const text = decodeXmlEntities(match[2]).replace(/\s+/g, ' ').trim();
    if (text) lines.push(`${formatTime(startSec)} ${text}`);
  }
  return lines.join('\n');
}

function decodeXmlEntities(s: string): string {
  return s
    .replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(Number(n)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;|&apos;/g, "'");
}

function formatTime(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `[${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}]`;
}
