import { proxiedFetch, type ProxyConfig } from './proxy';

// 通过 YouTube InnerTube API + timedtext 端点拉字幕。
// 流程：
//   1. POST /youtubei/v1/player（Android client 上下文）→ 拿到 captionTracks 列表
//   2. 优先选 zh-CN，没有则选第一条
//   3. GET captionTrack.baseUrl → 拿到字幕 XML
//   4. 正则解析 <text start="..." dur="...">内容</text> → 转成 [mm:ss] 行
//
// 调用模式：传 proxy 走 webshare 隧道，不传走原生 fetch（适合本地 dev 验证基础流程）。

export interface YouTubeFetchOptions {
  proxy?: ProxyConfig | null;
}

const INNERTUBE_URL = 'https://www.youtube.com/youtubei/v1/player?prettyPrint=false';
const ANDROID_UA = 'com.google.android.youtube/20.10.38 (Linux; U; Android 14)';
const ANDROID_CLIENT_VERSION = '20.10.38';

interface InnerTubePlayerResponse {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: Array<{
        baseUrl: string;
        languageCode?: string;
        kind?: string;
        name?: { simpleText?: string };
      }>;
    };
  };
  playabilityStatus?: { status?: string; reason?: string };
  videoDetails?: { title?: string };
}

export interface YouTubeSubtitleResult {
  text: string;                    // [mm:ss] 行格式
  languageCode: string;
  isAutoGenerated: boolean;
}

/**
 * 取 YouTube 字幕。失败时抛 Error。
 * 不做 fallback，由上层 subtitle.ts 编排兜底。
 */
export async function fetchYouTubeSubtitles(
  videoId: string,
  options: YouTubeFetchOptions = {}
): Promise<YouTubeSubtitleResult> {
  const player = await fetchInnerTubePlayer(videoId, options);

  if (player.playabilityStatus?.status && player.playabilityStatus.status !== 'OK') {
    throw new Error(`视频不可播放：${player.playabilityStatus.status} ${player.playabilityStatus.reason || ''}`);
  }

  const tracks = player.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  if (tracks.length === 0) {
    throw new Error('视频没有可用字幕轨');
  }

  const preferred = tracks.find(t => t.languageCode === 'zh-CN')
                 ?? tracks.find(t => t.languageCode === 'zh')
                 ?? tracks.find(t => t.languageCode?.startsWith('en'))
                 ?? tracks[0];

  const xml = await fetchTimedtextXml(preferred.baseUrl, options);
  const text = parseTimedtextXmlToLines(xml);
  if (!text.trim()) {
    throw new Error('字幕 XML 解析后为空');
  }

  return {
    text,
    languageCode: preferred.languageCode || 'unknown',
    isAutoGenerated: preferred.kind === 'asr'
  };
}

async function fetchInnerTubePlayer(
  videoId: string,
  options: YouTubeFetchOptions
): Promise<InnerTubePlayerResponse> {
  const body = JSON.stringify({
    context: {
      client: {
        clientName: 'ANDROID',
        clientVersion: ANDROID_CLIENT_VERSION,
        hl: 'zh-CN',
        gl: 'CN'
      }
    },
    videoId
  });

  const headers = {
    'Content-Type': 'application/json',
    'User-Agent': ANDROID_UA,
    'Accept': 'application/json'
  };

  let raw: string;
  let status: number;
  if (options.proxy) {
    const res = await proxiedFetch({
      url: INNERTUBE_URL,
      method: 'POST',
      headers,
      body
    }, options.proxy);
    raw = res.body;
    status = res.status;
  } else {
    const res = await fetch(INNERTUBE_URL, { method: 'POST', headers, body });
    raw = await res.text();
    status = res.status;
  }

  if (status !== 200) {
    throw new Error(`InnerTube HTTP ${status}：${raw.slice(0, 200)}`);
  }

  try {
    return JSON.parse(raw) as InnerTubePlayerResponse;
  } catch (e) {
    throw new Error(`InnerTube 响应不是合法 JSON：${(e as Error).message}`);
  }
}

async function fetchTimedtextXml(
  url: string,
  options: YouTubeFetchOptions
): Promise<string> {
  const headers = {
    'User-Agent': ANDROID_UA,
    'Accept': 'application/xml,text/xml,*/*'
  };

  let raw: string;
  let status: number;
  if (options.proxy) {
    const res = await proxiedFetch({ url, method: 'GET', headers }, options.proxy);
    raw = res.body;
    status = res.status;
  } else {
    const res = await fetch(url, { headers });
    raw = await res.text();
    status = res.status;
  }

  if (status !== 200) {
    throw new Error(`timedtext HTTP ${status}：${raw.slice(0, 200)}`);
  }
  return raw;
}

// 把 <text start="12.345" dur="2.1">内容</text> 拼成 [mm:ss] 行。
// XML 实体只处理 5 个常见字符 + 数字字符引用，够覆盖 YouTube 字幕里的常见转义。
export function parseTimedtextXmlToLines(xml: string): string {
  const lines: string[] = [];
  const regex = /<text\s+start="([\d.]+)"(?:\s+dur="[\d.]+")?[^>]*>([\s\S]*?)<\/text>/g;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(xml)) !== null) {
    const start = Number(match[1]);
    const raw = match[2];
    const text = decodeXmlEntities(raw).replace(/\s+/g, ' ').trim();
    if (text) {
      lines.push(`${formatTime(start)} ${text}`);
    }
  }
  return lines.join('\n');
}

function decodeXmlEntities(s: string): string {
  return s
    .replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(Number(n)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;|&apos;/g, "'");
}

function formatTime(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `[${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}]`;
}
